language: go

os:
  - linux

go:
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip

notifications:
  email:
    on_success: change
    on_failure: always

before_install:

install:
  - go get -u
  - go get -u golang.org/x/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

before_script:

script:
  - go vet ./...
  - diff <(goimports -d $(find . -type f -name '*.go' -not -path "*_easyjson*")) <(printf "")
  - diff <(golint ./...) <(printf "")
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_script:

after_success:

after_failure: